### ISSUE TITLE
Creating pipe: Too many open files

### ISSUE THREAD

**Issue by FrostyX** [emacs-slack/emacs-slack#583] opened 2023-06-20 13:51 UTC
**Describe the bug**
My `slack-start` command fails with:

```
[2023-06-20 15:43:22] [info] [redacted instance name] Slack Websocket Is Ready!
[2023-06-20 15:43:22] [info] [redacted instance name] Slack Command List Updated
error in process sentinel: make-process--with-editor-process-filter: Creating pipe: Too many open files
error in process sentinel: Creating pipe: Too many open files
Download Failed. STATUS: exit, EVENT: exited abnormally with code 125
, URL: https://emoji.slack-edge.com/T030G10V24F/schwa/2499b21b1d512990.png, NAME: /tmp/b80773febba540a063511f6ac2b16320.png, OUTPUT: 
```

**To Reproduce**

1. `M-x slack-start`
2. Wait ~20 seconds
3. Error

**Backtrace**

See above

**Expected behavior**

I want the command to finish successfully and connect me to Slack

**Screenshots**

Not applicable

**Environment:**
 - OS: Fedora 37
 - Emacs Version: 28.2
 - emacs-slack Version: 20211129.310

**Additional context**

I want to connect to a company instance, so I cannot share the hostname

**Comment by gravieure** [comment] 2023-10-19 17:47
You need to use [ulimit](https://ss64.com/bash/ulimit.html) to increase the number of files you can open.  This isn't an emacs-slack bug.

**Comment by sleep-walker** [comment] 2024-05-31 09:01
Well, I can hit this issue regardless how high the limit I set. Maybe it could be done in a way where the amount of opened files at the same time is not that huge?

**Comment by ag91** [comment] 2024-11-18 23:20
mmm is this still happening? I think it is an easy fix [here](https://github.com/ag91/emacs-slack/blob/master/slack-emoji.el#L82), we could batch the obtained emojis in groups of N and process over an idle-timer.
Anybody who is still interested in testing this if I patch it? I don't have so many emojis in my slack channels, strangely (I thought clojurians had a lot, but I didn't see the error)

**Comment by sleep-walker** [comment] 2024-11-19 00:03
If you can prepare branch, I can test it.

**Comment by ag91** [comment] 2024-11-19 00:23
cool, thanks. I will try in the week (I tried on the fly, but there is a little state `paths` which may requrie a bit of macro magic I think to make that code run after the last async computation)

**Comment by ag91** [comment] 2024-11-20 21:03
@sleep-walker could you give a try to https://github.com/emacs-slack/emacs-slack/commit/64f37e307d10f9bd7229077253ae0c710f8775cf on [this branch](https://github.com/emacs-slack/emacs-slack/tree/bugfix/583-reduce-file-descriptors-consumptions-due-to-emoji)?

You can set `slack-emoji-job-batch-size` and `slack-emoji-job-interval` to toggle how many emojis get downloaded at a time and every how many seconds respectively.

**Comment by ag91** [comment] 2024-11-20 22:43
mmm never mind I managed to reproduce while working on https://github.com/emacs-slack/emacs-slack/issues/520, there is still something wrong in my code

**Comment by ag91** [comment] 2024-11-20 23:26
okay, if you could test now it would be cool: I have fixed the issue and things seem to work well.
I increased the batch size so that it takes less: I added the default images so if you have many custom emojis this will take a while

**Comment by ag91** [comment] 2024-11-21 18:22
this seems unrelated: is your cookie set properly, could you check by running `slack-refresh-token`?

**Comment by ag91** [comment] 2024-11-22 00:19
merged in the change that fixed this for me, please reopen if this is not fixed for some reason.
@sleep-walker please open an issue if you struggle getting started after following the instructions in the readme (they changed from the original version because Slack changed the way client need to authenticate)

**Closed by ag91** 2024-11-22 00:19 UTC
Labels: bug

**Comment by sleep-walker** [comment] 2024-11-22 12:22
You are right, it's probably unrelated. Unfortunatelly, my `api_token` starts with `xoxc` and there is no `enterprise_api_token` in `TS.boot_data`. So I can't login anymore and thus can't verify the fix.

**Comment by ag91** [comment] 2024-11-23 12:20
@sleep-walker is it possible that you didn't follow the instructions after running `M-x slack-refresh-token`?
I have a xoxc token too and I am using emacs-slack.
Anyway, no need to test: I checked the fix and it works :sunny:
