### ISSUE TITLE
No Message in <channel>, fetching from server hangs forever

### ISSUE THREAD

**Issue by iris-garcia** [emacs-slack/emacs-slack#545] opened 2021-01-04 12:50 UTC
**Describe the bug**
When calling  `slack-group-select` and selecting a group (which probably has a lot of messages in the history), it does not show the group at all, the only message I see is: `No Message in <channel>, fetching from server`

**To Reproduce**
1. Call slack-group-select
2. Select a group with a huge history?
3. See how the buffer never gets created.

**Expected behavior**
A new buffer should be created with the group's messages.

**Environment:**
 - OS: Arch Linux
 - Emacs Version: 28.0.50
 - emacs-slack Version: 20200830.1021 - commit(1f6a40faec0d8d9c9de51c444508d05a3e995ccd)

**Comment by togakangaroo** [comment] 2021-01-10 22:50
seeing this too on Ubuntu 20, emacs 26.3 Restarting emacs seems to fix it

**Comment by andrew-hm** [comment] 2021-01-13 22:09
duplicate of https://github.com/yuya373/emacs-slack/issues/526

**Comment by ag91** [comment] 2024-11-19 00:31
the fixes should be in the latest version of emacs-slack

**Closed by ag91** 2024-11-19 00:31 UTC
Labels: bug
